[settings]
lockfile = true
lockfile_platforms = ["macos-arm64", "linux-arm64", "linux-x64"]
disable_backends = ["asdf", "vfox"]

[tools]
# CLI tools
"aqua:neovim/neovim" = "0.12.5"
"aqua:tmux/tmux-builds" = "3.7c"
"aqua:tree-sitter/tree-sitter" = "0.26.13"

"aqua:atuinsh/atuin" = "18.20.1"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:ClementTsang/bottom" = "0.14.9"
"npm:@openai/codex" = { version = "0.151.0", depends = ["node"] }
"aqua:dandavison/delta" = "0.19.2"
"cargo:eza" = { version = "0.23.5", depends = ["rust"] }
"aqua:sharkdp/fd" = "10.5.0"
"aqua:junegunn/fzf" = "0.74.3"
"aqua:cli/cli" = "2.98.0"                                         # Github cli
"gitlab:gitlab-org/cli" = "1.115.0"                               # Gitlab cli
"aqua:charmbracelet/glow" = "3.0.0"
"aqua:jqlang/jq" = "1.8.2"
"aqua:jesseduffield/lazygit" = "0.64.1"
"aqua:BurntSushi/ripgrep" = "15.2.0"
"aqua:starship/starship" = "1.26.0"
"aqua:google/yamlfmt" = "0.21.0"
"aqua:sxyazi/yazi" = "26.8.15"
"aqua:mikefarah/yq" = "4.53.6"
"aqua:ajeetdsouza/zoxide" = "0.10.0"

# Containers and Kubernetes
"aqua:abiosoft/colima" = "0.10.3"
"aqua:docker/cli" = "29.7.2"
"aqua:hadolint/hadolint" = "2.15.1"
"aqua:helm/helm" = "4.2.4"
"aqua:mrjosh/helm-ls" = "0.5.4"
"aqua:derailed/k9s" = "0.51.0"
"aqua:kubernetes-sigs/kind" = "0.33.0"
"aqua:yannh/kubeconform" = "0.8.0"

# Go
"core:go" = "1.27.0"
"aqua:mvdan/gofumpt" = "0.11.0"
"aqua:golangci/golangci-lint" = "2.13.2"
"go:golang.org/x/tools/cmd/goimports" = { version = "0.49.0", depends = ["go"] }
"go:github.com/fatih/gomodifytags" = { version = "1.17.0", depends = ["go"] }
"go:golang.org/x/tools/gopls" = { version = "0.23.0", depends = ["go"] }
"aqua:gotestyourself/gotestsum" = "1.13.0"
"go:github.com/josharian/impl" = { version = "1.5.0", depends = ["go"] }

# Python
"core:python" = "3.14.7"
"aqua:astral-sh/uv" = "0.12.7"
"npm:basedpyright" = { version = "1.39.10", depends = ["node"] }
"pipx:mypy" = { version = "2.3.1", uvx_args = "--python 3.14.7", depends = [
  "python",
  "aqua:astral-sh/uv",
] }
"pipx:robotcode" = { version = "2.7.0", extras = [
  "languageserver",
  "analyze",
  "lint",
], uvx_args = "--python 3.14.7 --with robotframework==7.3.2 --with robotframework-robocop==9.0.0", depends = [
  "python",
  "aqua:astral-sh/uv",
] }
"pipx:robotframework" = { version = "7.3.2", uvx_args = "--python 3.14.7", depends = [
  "python",
  "aqua:astral-sh/uv",
] }
"pipx:robotframework-robocop" = { version = "9.0.0", uvx_args = "--python 3.14.7 --with robotframework==7.3.2", depends = [
  "python",
  "aqua:astral-sh/uv",
] }
"aqua:astral-sh/ruff" = "0.16.5"

# Node.js
"core:node" = "24.20.0"

# Rest of LSPs
"aqua:LuaLS/lua-language-server" = "3.19.1"
"npm:vscode-langservers-extracted" = { version = "4.10.0", depends = ["node"] }
"npm:yaml-language-server" = { version = "1.24.0", depends = ["node"] }

# Rust
"core:rust" = "1.98.0"
"aqua:rust-lang/rust-analyzer" = "2026-08-24"
